spring:
  application:
    name: web-noise
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/sample
    username: echo
    password: q1w2e3r4
    hikari:
      connection-timeout: 3000
      idle-timeout: 6000
      max-lifetime: 18000
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
